# %% [markdown]
# # DKO Spatial Transcriptomics - Data Inspection
# Load and inspect `DKO_Tier1.h5ad` generated by `sc_analysis.py`.
# This file contains 328k cells from 7 samples (3 WT, 4 DKO) with
# Baysor segmentation, Harmony batch correction, and Tier1 cell type annotations.

# %%
import os
import anndata as ad
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sc.settings.set_figure_params(dpi=100, frameon=False)

PROJECT_DIR = "/data/work/Pourya/mmr_spatial"
os.chdir(PROJECT_DIR)

# %%
# Load the processed h5ad
DATA_PATH = os.path.join(PROJECT_DIR, "input", "DKO_results", "DKO_Tier1.h5ad")
adata = ad.read_h5ad(DATA_PATH)
print(adata)

# %% [markdown]
# ## Basic structure

# %%
# Observations (cells) metadata
print(f"Cells: {adata.n_obs:,}")
print(f"Genes: {adata.n_vars:,}")
print(f"\nobs columns: {list(adata.obs.columns)}")
print(f"\nobsm keys: {list(adata.obsm.keys())}")
print(f"layers: {list(adata.layers.keys())}")
print(f"uns keys: {list(adata.uns.keys())}")

# %%
# Sample and condition breakdown
print(adata.obs[["sample", "condition"]].drop_duplicates().sort_values("sample"))
print("\n--- Cells per sample ---")
print(adata.obs["sample"].value_counts())
print("\n--- Cells per condition ---")
print(adata.obs["condition"].value_counts())

# %%
# Cell type annotations
print("--- Tier1 cell types ---")
print(adata.obs["Tier1_celltype"].value_counts())
print("\n--- Tier1 groups ---")
print(adata.obs["Tier1_group"].value_counts())

# %% [markdown]
# ## QC metrics

# %%
# Counts and genes per cell
fig, axes = plt.subplots(1, 3, figsize=(12, 3))
axes[0].hist(adata.obs["total_counts"], bins=50)
axes[0].set_xlabel("Total counts")
axes[0].set_ylabel("Cells")
axes[1].hist(adata.obs["n_genes_by_counts"], bins=50)
axes[1].set_xlabel("Genes detected")
axes[2].hist(adata.obs["avg_assignment_confidence"], bins=50)
axes[2].set_xlabel("Assignment confidence")
plt.tight_layout()
plt.show()

# %%
# QC by sample
sc.pl.violin(adata, keys=["total_counts", "n_genes_by_counts"], groupby="sample", rotation=45)

# %% [markdown]
# ## Embeddings

# %%
# UMAP colored by condition and cell type
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sc.pl.umap(adata, color="condition", ax=axes[0], show=False, title="Condition")
sc.pl.umap(adata, color="Tier1_celltype", ax=axes[1], show=False, title="Cell Type", size=2)
plt.tight_layout()
plt.show()

# %%
# UMAP by sample to check batch correction
sc.pl.umap(adata, color="sample", title="Sample (Harmony corrected)")

# %% [markdown]
# ## Spatial coordinates

# %%
# Spatial plot for one sample
sample_id = "DKO1"
adata_sub = adata[adata.obs["sample"] == sample_id]
sc.pl.spatial(adata_sub, color="Tier1_celltype", spot_size=15, title=f"{sample_id} - Cell Types")

# %%
# Spatial overview of all samples
fig, axes = plt.subplots(2, 4, figsize=(24, 12))
for ax, sample_id in zip(axes.ravel(), adata.obs["sample"].cat.categories):
    adata_s = adata[adata.obs["sample"] == sample_id]
    sc.pl.spatial(adata_s, color="Tier1_celltype", spot_size=10, ax=ax, show=False, title=sample_id, legend_loc=None)
# hide unused subplot if odd number of samples
if len(adata.obs["sample"].cat.categories) < axes.size:
    axes.ravel()[-1].axis("off")
plt.tight_layout()
plt.show()

# %% [markdown]
# ## Spatial marker expression

# %%
# Marker genes for spatial visualization
spatial_markers = {
    "Klrk1": "NK/CD8 activation",
    "Gzmb": "Cytotoxicity",
    "Prf1": "Cytotoxicity",
    "Cxcl16": "Chemokine (Macrophage)",
    "Cxcr6": "Chemokine receptor (T/NK)",
    "Il15": "Cytokine signaling",
}
spatial_marker_genes = [g for g in spatial_markers if g in adata.var_names]

# %%
# Spatial marker expression per sample
import matplotlib.colors as mcolors

grey_red_cmap = mcolors.LinearSegmentedColormap.from_list("grey_red", ["#e0e0e0", "grey", "red"])

sample_id = "DKO1"
adata_sub = adata[adata.obs["sample"] == sample_id]

n_markers = len(spatial_marker_genes)
fig, axes = plt.subplots(1, n_markers + 1, figsize=(5 * (n_markers + 1), 5))

# First panel: cell types
sc.pl.spatial(adata_sub, color="Tier1_celltype", spot_size=15, ax=axes[0], show=False, title=f"{sample_id} - Cell Types", legend_loc=None)

# Remaining panels: marker genes
for i, gene in enumerate(spatial_marker_genes):
    sc.pl.spatial(adata_sub, color=gene, spot_size=15, cmap=grey_red_cmap, ax=axes[i + 1], show=False, title=gene)

plt.tight_layout()
plt.show()

# %%
# Compare marker spatial expression across all samples (one gene at a time)
gene_to_plot = "Klrk1"

samples = adata.obs["sample"].cat.categories.tolist()
fig, axes = plt.subplots(2, 4, figsize=(24, 12))
for ax, sid in zip(axes.ravel(), samples):
    adata_s = adata[adata.obs["sample"] == sid]
    sc.pl.spatial(adata_s, color=gene_to_plot, spot_size=10, cmap=grey_red_cmap, ax=ax, show=False, title=f"{sid} - {gene_to_plot}")
if len(samples) < axes.size:
    axes.ravel()[-1].axis("off")
plt.tight_layout()
plt.show()

# %%
# Spatial: Tumor + CD8 overlay with Gzmb expression
sample_id = "DKO1"
adata_sub = adata[adata.obs["sample"] == sample_id]

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Panel 1: Tumor region
sc.pl.spatial(adata_sub, color="Tier1_celltype", groups=["Tumor"], spot_size=15, na_color="lightgrey", ax=axes[0], show=False, title=f"{sample_id} - Tumor")

# Panel 2: CD8+ T cells
sc.pl.spatial(adata_sub, color="Tier1_celltype", groups=["CD8+ T"], spot_size=15, na_color="lightgrey", ax=axes[1], show=False, title=f"{sample_id} - CD8+ T")

# Panel 3: Gzmb expression
sc.pl.spatial(adata_sub, color="Gzmb", spot_size=15, cmap=grey_red_cmap, ax=axes[2], show=False, title=f"{sample_id} - Gzmb")

plt.tight_layout()
plt.show()

# %% [markdown]
# ## Gene expression check

# %%
# Check a few marker genes in the normalized expression
markers = ["Klrk1", "Gzmb", "Prf1", "Cxcl16", "Il15"]
available = [g for g in markers if g in adata.var_names]
sc.pl.umap(adata, color=available, cmap="Reds", size=2)

# %%
# Dotplot of markers by cell type
sc.pl.dotplot(adata, var_names=available, groupby="Tier1_celltype", standard_scale="var")

# %% [markdown]
# ## Cell type proportions by condition

# %%
props = pd.crosstab(adata.obs["condition"], adata.obs["Tier1_celltype"], normalize="index")
props.T.plot(kind="barh", stacked=True, figsize=(8, 6))
plt.xlabel("Proportion")
plt.title("Cell type proportions by condition")
plt.legend(title="Condition", bbox_to_anchor=(1.05, 1))
plt.tight_layout()
plt.show()